### ISSUE TITLE
Trac unable to load plugin

### ISSUE THREAD

**Issue by pmsudhi** [mandic-cloud/trac-slack-plugin#6]
Installed the egg file in the plugin directory, doen configuration in trac.ini. the added plugin is not listed in available plugin section in admin area. The log file says
`File "build\bdist.win32\egg\trac\web\main.py", line 554, in _dispatch_request
    dispatcher.dispatch(req)
  File "build\bdist.win32\egg\trac\web\main.py", line 203, in dispatch
    if handler.match_request(req):
  File "c:\users\user\bitnami_trac_stack_projects\wasp3d\plugins\testmanager-1.8.2-py2.7.egg\testmanager\api.py", line 282, in match_request
    type = req.args.get('type', '')
  File "build\bdist.win32\egg\trac\web\api.py", line 355, in __getattr__
    value = self.callbacks[name](self)
  File "build\bdist.win32\egg\trac\web\api.py", line 338, in <lambda>
    'args': lambda req: arg_list_to_args(req.arg_list),
  File "build\bdist.win32\egg\trac\web\api.py", line 355, in __getattr__
    value = self.callbacks[name](self)
  File "build\bdist.win32\egg\trac\web\api.py", line 725, in _parse_arg_list
    fs = _FieldStorage(fp, environ=self.environ, keep_blank_values=True)
  File "C:\Bitnami\trac-1.0.9-0\python\lib\cgi.py", line 505, in __init__
    self.read_urlencoded()
  File "C:\Bitnami\trac-1.0.9-0\python\lib\cgi.py", line 606, in read_urlencoded
    qs = self.fp.read(self.length)
IOError: request data read error
2016-02-16 09:09:17,680 Trac[loader] ERROR: Skipping "slack_notification = slack_notification": 
Traceback (most recent call last):
  File "build\bdist.win32\egg\trac\loader.py", line 68, in _load_eggs
    entry.load(require=True)
  File "build\bdist.win32\egg\pkg_resources.py", line 2184, in load
    ['__name__'])
  File "build\bdist.win32\egg\slack_notification\__init__.py", line 2, in <module>
ImportError: No module named requests
2016-02-16 09:10:08,059 Trac[loader] ERROR: Skipping "slack_notification = slack_notification": 
Traceback (most recent call last):
  File "build\bdist.win32\egg\trac\loader.py", line 68, in _load_eggs
    entry.load(require=True)
  File "build\bdist.win32\egg\pkg_resources.py", line 2184, in load
    ['__name__'])
  File "build\bdist.win32\egg\slack_notification\__init__.py", line 2, in <module>
ImportError: No module named requests
`

**Comment by pmsudhi** [comment]
Sorry. Was in Hurry. PIP requests was no there. Issue resolved now
